---
apiVersion: v1
kind: Service
metadata:
  name: edgeinflux
  namespace: rssreader
  labels:
    name: edgeinflux
spec:
  type: NodePort
  ports:
  - port: 9090
    name: http
    nodePort: 31000
  selector:
    name: edgeinflux
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: edgeinflux
  namespace: rssreader
  labels:
    name: edgeinflux
spec:
  replicas: 1
  selector:
    name: edgeinflux
  template:
    metadata:
      labels:
        name: edgeinflux
    spec:
      containers:
      - name: edgeinflux
        image: timz/rssedge
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: "0.5"
            memory: 500M
          limits:
            cpu: "1"
            memory: 2000M
---
