apiVersion: v1
kind: ReplicationController
metadata:
  name: edgeinflux
  labels:
    name: edgeinflux
spec:
  replicas: 1
  selector:
    name: edgeinflux
  template:
    metadata:
      labels:
        name: edgeinflux
    spec:
      containers:
        - name: edgeinflux
          image: timz/rssedge
          ports:
            - containerPort: 9090
