apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-mon
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
        #version: v6
    spec:
      containers:
      - name: heapster-mon
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://influxdb-mon:8086
        - --metric_resolution=60s
        ports:
        - containerPort: 8082
        - containerPort: 80
