kind: ReplicationController
apiVersion: v1
metadata:
  name: cpu-stress
  labels:
    name: cpu-stress
spec:
  selector:
    name: cpu-stress
  template:
    metadata:
      labels:
        name: cpu-stress
    spec:
      containers:
        - name: cpu-stress
          image: timz/stress
          imagePullPolicy: Always
          args: ["--cpu", "10"]
      nodeSelector:
        nodeassignment: 10.0.11.62