kind: ReplicationController
apiVersion: v1
metadata:
  name: mem-stress
  labels:
    name: mem-stress
spec:
  selector:
    name: mem-stress
  template:
    metadata:
      labels:
        name: mem-stress
    spec:
      containers:
        - name: mem-stress
          image: timz/stress
          imagePullPolicy: Always
          args: ["--vm-bytes", "600M", "--vm-keep", "-m", "1"]
          resources:
              requests:
                cpu: "0.3"
                memory: 700M
              limits:
                cpu: "1"
                memory: 2000M
      nodeSelector:
        nodeassignment: 10.0.11.64