
kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  selector:
    name: locust
    role: master
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
        - name: locust
          image: timz/rsslocust
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_URL
              value: http://edge:9090
            - name: INFLUXDB_URL
              value: influxdb
            - name: INFLUXDB_PORT
              value: '8086'
            - name: LOCUST_FILE_URL
              value: 'https://raw.githubusercontent.com/Timzzz/K8sfp/master/deployment/lcust/locustfile.py'
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
      nodeSelector:
          nodeassignment: 10.0.11.63